#!/bin/bash

if [ remove = "$1" ]; then 
   dpkg-divert --package deskbar2 --remove --rename --divert /usr/lib/libwnck-1.so.22.3.13.real /usr/lib/libwnck-1.so.22.3.13 
   dpkg-divert --package deskbar2 --remove --rename --divert /usr/lib/libwnck-1.so.22.real /usr/lib/libwnck-1.so.22
   dpkg-divert --package deskbar2 --remove --rename --divert /usr/lib/pyshared/python2.6/gtk-2.0/wnck.so.real /usr/lib/pyshared/python2.6/gtk-2.0/wnck.so
fi  
