#!/bin/bash

if [ install = "$1" -o upgrade = "$1" ]; then 
   dpkg-divert --package deskbar2 --add --rename --divert /usr/lib/libwnck-1.so.22.3.13.real /usr/lib/libwnck-1.so.22.3.13
   dpkg-divert --package deskbar2 --add --rename --divert /usr/lib/libwnck-1.so.22.real /usr/lib/libwnck-1.so.22
   dpkg-divert --package deskbar2 --add --rename --divert /usr/lib/pyshared/python2.6/gtk-2.0/wnck.so.real /usr/lib/pyshared/python2.6/gtk-2.0/wnck.so
   dpkg-divert --package deskbar2 --add --rename --divert /usr/lib/python2.6/dist-packages/gtk-2.0/wnck.so.real /usr/lib/python2.6/dist-packages/gtk-2.0/wnck.so
fi   
